CREATE DATABASE IF NOT EXISTS skeleton_db;

CREATE TABLE IF NOT EXISTS tb_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(36) UNIQUE NOT NULL,
  firstname VARCHAR(255) UNIQUE NOT NULL,
  lastname VARCHAR(255) UNIQUE NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);
