@startuml
title DELETE delete token - POST erp-ext-auth-service
actor Requestor #deepskyblue

box "erp-ext-auth-service ms" #powderblue
  entity "delete token" as getSvc #deepskyblue
end box

box "Database" #GreenYellow
  entity "SQLite" as db #Grey
end box


Group DeleteToken
Requestor -> getSvc: DELETE /api/v1/delete
activate getSvc
opt check params
alt if params token_id is empty
Requestor <- getSvc: Response Error
deactivate getSvc
end alt
end opt

opt Delete token from sqlite

getSvc -> db: Delete
activate db
note left of db
<b>SQL</b>
DELETE FROM auth_dtl WHERE id = ?
end note
getSvc <- db: Return error
deactivate db

alt if sql error
activate getSvc
Requestor <- getSvc:
note left of getSvc
<b>Response</b>
HTTPStatusCode 500 With message "error"
end note
end alt

alt if sql not error
Requestor <- getSvc:
note left of getSvc
<b>Response</b>
HTTPStatusCode 200 With message "success"
end note
deactivate getSvc
end alt

end opt


end Group
hide footbox
@enduml


